use crate::resp::Resp;
use bytes::Bytes;
use crate::cmd::{get_command_keys, command_name};

struct CommandInfo {
    name: &'static str,
    arity: i64,
    flags: &'static [&'static str],
    first_key: i64,
    last_key: i64,
    step: i64,
}

const COMMAND_TABLE: &[CommandInfo] = &[
    CommandInfo {
        name: "ping",
        arity: -1,
        flags: &["fast", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "echo",
        arity: 2,
        flags: &["fast", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "hello",
        arity: -1,
        flags: &["fast", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "reset",
        arity: 1,
        flags: &["fast", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "select",
        arity: 2,
        flags: &["fast", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "auth",
        arity: 2,
        flags: &["fast", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "multi",
        arity: 1,
        flags: &["noscript"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "exec",
        arity: 1,
        flags: &["noscript"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "discard",
        arity: 1,
        flags: &["noscript"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "set",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "setnx",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "setex",
        arity: 4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "psetex",
        arity: 4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "getset",
        arity: 3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "getdel",
        arity: 2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "getex",
        arity: -2,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "getrange",
        arity: 4,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "setrange",
        arity: 4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "mset",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 2,
    },
    CommandInfo {
        name: "msetnx",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 2,
    },
    CommandInfo {
        name: "del",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "unlink",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "exists",
        arity: -2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "type",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "rename",
        arity: 3,
        flags: &["write"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "renamenx",
        arity: 3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "move",
        arity: 3,
        flags: &["write"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "swapdb",
        arity: 3,
        flags: &["write", "admin"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "persist",
        arity: 2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "get",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "mget",
        arity: -2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "incr",
        arity: 2,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "decr",
        arity: 2,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "incrby",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "incrbyfloat",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "decrby",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "append",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "strlen",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "stralgo",
        arity: -2,
        flags: &["readonly", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "lpush",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "lpushx",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "rpush",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "rpushx",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "lpop",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "rpop",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "blpop",
        arity: -3,
        flags: &["write", "noscript", "blocking"],
        first_key: 1,
        last_key: -2,
        step: 1,
    },
    CommandInfo {
        name: "brpop",
        arity: -3,
        flags: &["write", "noscript", "blocking"],
        first_key: 1,
        last_key: -2,
        step: 1,
    },
    CommandInfo {
        name: "blmove",
        arity: 6,
        flags: &["write", "noscript", "blocking"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "lmove",
        arity: 5,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "lindex",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "linsert",
        arity: 5,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "lrem",
        arity: 4,
        flags: &["write"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "lpos",
        arity: -3,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "ltrim",
        arity: 4,
        flags: &["write"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "llen",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "lrange",
        arity: 4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hset",
        arity: -4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hsetnx",
        arity: 4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hincrby",
        arity: 4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hincrbyfloat",
        arity: 4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hget",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hgetall",
        arity: 2,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hmset",
        arity: -4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hmget",
        arity: -3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hdel",
        arity: -3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hexists",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hlen",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hkeys",
        arity: 2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hvals",
        arity: 2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hstrlen",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hrandfield",
        arity: -2,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "hscan",
        arity: -3,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "sadd",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "srem",
        arity: -3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "sismember",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "smembers",
        arity: 2,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "scard",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "spop",
        arity: -2,
        flags: &["write", "random", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "srandmember",
        arity: -2,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "sscan",
        arity: -3,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "smove",
        arity: 4,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "sinter",
        arity: -2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "sinterstore",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "sunion",
        arity: -2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "sunionstore",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "sdiff",
        arity: -2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "sdiffstore",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "zadd",
        arity: -4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zincrby",
        arity: 4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zrem",
        arity: -3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zscore",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zcard",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zrank",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zrevrank",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zrange",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zrevrange",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zrangebyscore",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zrangebylex",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zcount",
        arity: 4,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zlexcount",
        arity: 4,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zpopmin",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "bzpopmin",
        arity: -3,
        flags: &["write", "noscript", "blocking"],
        first_key: 1,
        last_key: -2,
        step: 1,
    },
    CommandInfo {
        name: "zpopmax",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "bzpopmax",
        arity: -3,
        flags: &["write", "noscript", "blocking"],
        first_key: 1,
        last_key: -2,
        step: 1,
    },
    CommandInfo {
        name: "zscan",
        arity: -3,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zrandmember",
        arity: -2,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zunion",
        arity: -3,
        flags: &["readonly", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "zunionstore",
        arity: -4,
        flags: &["write", "denyoom", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "zinter",
        arity: -3,
        flags: &["readonly", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "zinterstore",
        arity: -4,
        flags: &["write", "denyoom", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "zdiff",
        arity: -3,
        flags: &["readonly", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "zdiffstore",
        arity: -4,
        flags: &["write", "denyoom", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "sdiffstore",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "pfadd",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "pfcount",
        arity: -2,
        flags: &["readonly"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "pfmerge",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "geoadd",
        arity: -5,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "geodist",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "geohash",
        arity: -2,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "geopos",
        arity: -2,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "georadius",
        arity: -6,
        flags: &["write", "movablekeys"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "georadiusbymember",
        arity: -5,
        flags: &["write", "movablekeys"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "geosearch",
        arity: -3,
        flags: &["readonly", "movablekeys"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "geosearchstore",
        arity: -4,
        flags: &["write", "denyoom", "movablekeys"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "expire",
        arity: 3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "pexpire",
        arity: 3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "expireat",
        arity: 3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "pexpireat",
        arity: 3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "ttl",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "pttl",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "flushdb",
        arity: -1,
        flags: &["write"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "flushall",
        arity: -1,
        flags: &["write"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "dbsize",
        arity: 1,
        flags: &["readonly", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "keys",
        arity: 2,
        flags: &["readonly", "sort_for_script"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "scan",
        arity: -2,
        flags: &["readonly", "random"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "save",
        arity: 1,
        flags: &["admin", "noscript"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "bgsave",
        arity: -1,
        flags: &["admin", "noscript"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "shutdown",
        arity: -1,
        flags: &["admin", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "command",
        arity: -1,
        flags: &["random", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "config",
        arity: -2,
        flags: &["admin", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "memory",
        arity: -2,
        flags: &["random", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "info",
        arity: -1,
        flags: &["random", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "eval",
        arity: -3,
        flags: &["noscript", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "evalsha",
        arity: -3,
        flags: &["noscript", "movablekeys"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "script",
        arity: -2,
        flags: &["noscript"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "xadd",
        arity: -5,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xlen",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xrange",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xrevrange",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xdel",
        arity: -3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xtrim",
        arity: -4,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xread",
        arity: -4,
        flags: &["readonly", "blocking"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xgroup",
        arity: -2,
        flags: &["write", "denyoom"],
        first_key: 2,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "xreadgroup",
        arity: -7,
        flags: &["write", "blocking"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xack",
        arity: -4,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xinfo",
        arity: -2,
        flags: &["readonly", "random"],
        first_key: 2,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "publish",
        arity: 3,
        flags: &["pubsub", "fast", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "subscribe",
        arity: -2,
        flags: &["pubsub", "noscript", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "unsubscribe",
        arity: -1,
        flags: &["pubsub", "noscript", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "psubscribe",
        arity: -2,
        flags: &["pubsub", "noscript", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "punsubscribe",
        arity: -1,
        flags: &["pubsub", "noscript", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "pubsub",
        arity: -2,
        flags: &["pubsub", "random", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "bgrewriteaof",
        arity: 1,
        flags: &["admin"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "client",
        arity: -2,
        flags: &["admin"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "monitor",
        arity: 1,
        flags: &["admin", "noscript", "loading"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "setbit",
        arity: 4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "getbit",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "bitcount",
        arity: -2,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "bitpos",
        arity: -3,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "bitop",
        arity: -4,
        flags: &["write", "denyoom"],
        first_key: 2,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "bitfield",
        arity: -2,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xpending",
        arity: -3,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xclaim",
        arity: -6,
        flags: &["write"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "xautoclaim",
        arity: -6,
        flags: &["write"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "watch",
        arity: -2,
        flags: &["noscript", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "unwatch",
        arity: 1,
        flags: &["noscript", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "acl",
        arity: -2,
        flags: &["admin", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "slowlog",
        arity: -2,
        flags: &["admin"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "dump",
        arity: 2,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "restore",
        arity: -4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "touch",
        arity: -2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandInfo {
        name: "sort",
        arity: -2,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "sort_ro",
        arity: -2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "copy",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "object",
        arity: -2,
        flags: &["readonly", "random"],
        first_key: 2,
        last_key: 2,
        step: 1,
    },
    CommandInfo {
        name: "smismember",
        arity: -3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "zmscore",
        arity: -3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandInfo {
        name: "lastsave",
        arity: 1,
        flags: &["random", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "role",
        arity: 1,
        flags: &["noscript", "fast", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "time",
        arity: 1,
        flags: &["random", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandInfo {
        name: "latency",
        arity: -2,
        flags: &["admin", "noscript", "loading", "stale"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
];

pub fn command(items: &[Resp]) -> Resp {
    if items.len() > 1 {
        let subcommand = match &items[1] {
            Resp::BulkString(Some(b)) => String::from_utf8_lossy(b).to_uppercase(),
            Resp::SimpleString(s) => String::from_utf8_lossy(s).to_uppercase(),
            _ => return Resp::Error("ERR syntax error".to_string()),
        };

        match subcommand.as_str() {
            "COUNT" => {
                return Resp::Integer(COMMAND_TABLE.len() as i64);
            }
            "INFO" => {
                let mut commands = Vec::new();
                if items.len() == 2 {
                    // Return all info
                    for cmd in COMMAND_TABLE {
                        commands.push(get_command_info(cmd));
                    }
                } else {
                    for i in 2..items.len() {
                        let name = match &items[i] {
                            Resp::BulkString(Some(b)) => String::from_utf8_lossy(b).to_lowercase(),
                            Resp::SimpleString(s) => String::from_utf8_lossy(s).to_lowercase(),
                            _ => continue,
                        };
                        if let Some(cmd) = COMMAND_TABLE.iter().find(|c| c.name == name) {
                            commands.push(get_command_info(cmd));
                        } else {
                            commands.push(Resp::BulkString(None));
                        }
                    }
                }
                return Resp::Array(Some(commands));
            }
            "GETKEYS" => {
                if items.len() < 3 {
                    return Resp::Error("ERR wrong number of arguments for 'command|getkeys' command".to_string());
                }
                let cmd_bytes = match &items[2] {
                    Resp::BulkString(Some(b)) => b,
                    Resp::SimpleString(s) => s,
                    _ => return Resp::Error("ERR invalid command name".to_string()),
                };
                let cmd_type = command_name(cmd_bytes);
                if cmd_type == crate::cmd::Command::Unknown {
                    return Resp::Error(format!("ERR Unknown command '{}'", String::from_utf8_lossy(cmd_bytes)));
                }

                let keys = get_command_keys(cmd_type, &items[2..]);
                let mut res = Vec::new();
                for key in keys {
                    res.push(Resp::BulkString(Some(Bytes::from(key))));
                }
                return Resp::Array(Some(res));
            }
            "HELP" => {
                let help = vec![
                    "COMMAND - Return details about all Redis commands.",
                    "COMMAND COUNT - Return the total number of commands.",
                    "COMMAND INFO <command-name> [<command-name> ...] - Return details about specific commands.",
                    "COMMAND GETKEYS <command> <arg> [<arg> ...] - Extract keys from a given command.",
                    "COMMAND HELP - Prints this help message.",
                ];
                let mut res = Vec::new();
                for line in help {
                    res.push(Resp::SimpleString(Bytes::from(line)));
                }
                return Resp::Array(Some(res));
            }
            _ => return Resp::Error(format!("ERR unknown subcommand or wrong number of arguments for 'COMMAND {}'", subcommand)),
        }
    }

    let mut commands = Vec::new();
    for cmd in COMMAND_TABLE {
        commands.push(get_command_info(cmd));
    }

    Resp::Array(Some(commands))
}

fn get_command_info(cmd: &CommandInfo) -> Resp {
    let mut info = Vec::new();
    info.push(Resp::SimpleString(Bytes::from(cmd.name)));
    info.push(Resp::Integer(cmd.arity));
    
    let mut flags = Vec::new();
    for flag in cmd.flags {
        flags.push(Resp::SimpleString(Bytes::from(*flag)));
    }
    info.push(Resp::Array(Some(flags)));

    info.push(Resp::Integer(cmd.first_key));
    info.push(Resp::Integer(cmd.last_key));
    info.push(Resp::Integer(cmd.step));

    Resp::Array(Some(info))
}

pub fn is_write_command(name: &str) -> bool {
    let name_lower = name.to_lowercase();
    for cmd in COMMAND_TABLE {
        if cmd.name == name_lower {
            for flag in cmd.flags {
                if *flag == "write" {
                    return true;
                }
            }
        }
    }
    false
}

pub fn is_blocking_command(name: &str) -> bool {
    let name_lower = name.to_lowercase();
    for cmd in COMMAND_TABLE {
        if cmd.name == name_lower {
            for flag in cmd.flags {
                if *flag == "blocking" {
                    return true;
                }
            }
        }
    }
    false
}
